# Generated by Django 5.2.1 on 2025-05-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auraapp', '0002_categoria_cliente_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(default='Descrição', max_length=300),
        ),
    ]
