# Generated by Django 5.2.1 on 2025-05-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auraapp', '0003_categoria_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='./static/blazer.png', upload_to='./static/'),
        ),
    ]
