# Generated by Django 5.2.1 on 2025-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auraapp', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
