# Generated by Django 5.2.1 on 2025-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auraapp', '0005_rename_cliente_pedido_cliente_pedido_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='emAlta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='./static/blazer.png', upload_to='./auraapp/static'),
        ),
    ]
