# Generated by Django 5.2.1 on 2025-05-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auraapp', '0006_produto_emalta_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='./auraapp/static/blazer.png', upload_to='./auraapp/static'),
        ),
    ]
