# Generated by Django 5.2.1 on 2025-05-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auraapp', '0008_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tamanho',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
